config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  resources :users do
    resources :posts
  end

  resource :sessions, only: [:new, :create, :destroy]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # delete '/logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController <  ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
    respond_to do |format|
      format.js{render "new"}
      format.html
    end
  end

  def create
    @user = User.find(params[:user_id])
    p params
    # @post = Post.new(post_params, user_id: @user.id)
    @post = @user.posts.new(post_params)
    if @post.save
      respond_to do |format|
        format.js{render 'show'}
        format.html {render 'show'}
      end
      # redirect_to user_post_path(@user.id, @post.id)
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController <  ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/header' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<%= link_to 'Sign up', new_user_path %> |
<%= link_to 'Log in', new_sessions_path %> |
<%= link_to 'Log out', '/logout' %>

app/views/posts/_form.html.erb
<div class="save-form">
<%= form_for :post, url: user_posts_path(@user.id), remote: true, method: 'post' do |f| %>

    <%= f.label :title %><br>
    <%= f.text_field :title %><br>

    <%= f.label :body %><br>
    <%= f.text_area(:body, size: '50x10')%><br>


    <%= f.submit %>
<% end %>
</div>

app/views/posts/_postList.html.erb
<li>
  <h1> <%= @post.title %> </h1>
  <p> <%= @post.body %> </p>
</li>

app/views/posts/index.html.erb
<ul class="post-container" style="align-content: center;">
<% postMatrix = @posts.each_slice(4).to_a %>
<% len = @posts.length/4 %>
<% len.times do |row| %>
  <% postMatrix[row].each do |post| %>
  <div style="width: 25%; display: inline-block;">
     <li>
        <h1><%= post.title %></h2><br>
        <p><%= post.body %><br></p>
    </li>
  </div>
  <% end %>
<% end %>
</div>
</ul>

<%= link_to 'Create a New Post', new_user_post_path, remote: true, id: "new-post-link", class: 'btn btn-danger' %>

app/views/posts/new.html.erb
<%= render(:partial => 'posts/form', :locals => {:user => @user}) %>

app/views/posts/new.js.erb
$('.post-container').append("<%= j render 'form'%>");
$('#new-post-link').hide();

app/views/posts/show.html.erb
<br>
<hr />
<h1><%= @post.title %></h1>
<br>
<%= @post.body %>

app/views/posts/show.js.erb
// console.log("<%= @post.title %>")
 $('.post-container').append("<%= j render 'postList'%>");
 $('.save-form').hide();
 $('#new-post-link').show()

app/views/users/_form.html.erb
<%= form_for :user, url: users_path, method: 'post' do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>

    <%= f.label :email %><br>
    <%= f.text_field :email %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render "users/form" %>